name: Deploy Java App to Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        cd app
        mvn clean package
        ls -la target/
        mv target/app.war ../app.war

    - name: Verify app.war
      run: |
        ls -la
        if [ -f app.war ]; then
          echo "app.war found"
        else
          echo "Error: app.war not found"
          exit 1
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init & Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
        ACTIONS_STEP_DEBUG: true
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve
